env:
  SFTP_HOST: ${{ secrets.FTP_SERVER }}
  SFTP_PORT: ${{ secrets.FTP_PORT }}
  SFTP_USER: ${{ secrets.FTP_USERNAME }}
  SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  
on: 
  push:
    branches:
      - master

name: "🚀 Deploy to production"
jobs:
  deploy:
    name: "🚚 Deploy sourcecode to production"
    runs-on: ubuntu-latest
    steps:
    - name: "⌛ Checking out the code"
      uses: actions/checkout@v3
    - name: "⚙️ Polishing the gears"
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: "📦 Getting dependencies (1/2)"
      run: npm install dotenv
    - name: "📦 Getting dependencies (2/2)"
      run: npm install ssh2-sftp-client
    - name: "📁 Sending project files to production"
      run: npm run deploy
      